version: "2"

services:
  app:
    build: .
    container_name: challenge-server
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:example.seclab.dais.unive.it"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"

  traefik:
    image: "traefik:v1.7"
    container_name: "traefik"
    ports:
      - 80:80
    command:
      - "--docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
